/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/trips/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search for available bus trips
         * @description Retrieve a list of bus trips based on source, destination, and travel date with optional filters and sorting.
         */
        get: operations["searchTrips"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/getBookingsInfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Operator Manifest
         * @description Returns the full manifest for a specific Operator.
         *     Data is grouped by Bus -> Trips -> Passengers.
         */
        get: operations["getBookingsInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BusSearchResult: {
            /** @example KPN Travels */
            bus_name?: string;
            /** @example 101 */
            bus_id?: number;
            /**
             * @description List of all stops on this route
             * @example [
             *       "Madurai",
             *       "Trichy",
             *       "Villupuram",
             *       "Chennai"
             *     ]
             */
            stops?: string[];
            /** @example 505 */
            trip_id?: number;
            /**
             * Format: date
             * @example 2025-12-25
             */
            trip_date?: string;
            /** @example 20 */
            path_id?: number;
            /**
             * Format: float
             * @example 4.5
             */
            rating?: number;
            /**
             * @description Estimated departure time at the user's pickup point
             * @example 2025-12-25T18:30:00.000Z
             */
            departure_time?: string;
            /**
             * @description Estimated arrival time at the user's drop point
             * @example 2025-12-26T06:00:00.000Z
             */
            arrival_time?: string;
            /**
             * @description Distance in KM between pickup and drop
             * @example 450.5
             */
            distance?: number;
            /**
             * @description Ticket cost for this specific leg of the journey
             * @example 850
             */
            price?: number;
            /** @example 12 */
            available_seats?: number;
            /** @example AC Sleeper */
            bus_type?: string;
        };
        OperatorBusManifest: {
            /** @example AC Sleeper */
            bus_type?: string;
            /** @example TN-01-AA-1001 */
            bus_number?: string;
            /** @description List of passengers on this bus. */
            passengers_list?: {
                /** @example 5001 */
                trip_id?: number;
                /** @example 9001 */
                ticket_id?: number;
                /** @example 1001 */
                booking_id?: number;
                /** @example Rajesh Kumar */
                passenger_name?: string;
                /** @example A1 */
                seat_number?: string;
                /**
                 * @example good
                 * @enum {string}
                 */
                seat_condition?: "good" | "repair" | "maintenance" | "damaged";
                /** @example 9876543210 */
                contact_number?: string;
                /** @example Chennai - Madurai */
                route_name?: string;
                /** @example Chennai Koyambedu */
                pickup_point?: string;
                /** @example Madurai Mattuthavani */
                drop_point?: string;
                /**
                 * Format: date-time
                 * @example 2025-12-10 21:00:00.000000
                 */
                departure_time?: string;
                /**
                 * Format: date-time
                 * @example 2025-12-01 10:00:00.000000
                 */
                booking_date?: string;
                /** @example Confirmed */
                booking_status?: string;
                /**
                 * Format: float
                 * @example 600
                 */
                amount_paid?: number;
                /**
                 * @description Total passengers on this specific trip.
                 * @example 3
                 */
                total_trip_bookings?: number;
            }[];
        };
        /** @description Standard error wrapper for all non-2xx responses. */
        ErrorResponse: {
            /** @example 400 */
            status: number;
            /** @example Bad Request */
            error: string;
            /** @example Invalid date format. */
            message: string;
            /** @example VAL_001 */
            code?: string;
        };
    };
    responses: {
        /** @description Bad Request – Invalid inputs (e.g., date format or missing ID). */
        BadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unauthorized – missing or invalid authentication credentials. */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Forbidden – authenticated but not allowed to access this resource. */
        ForbiddenError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error – unexpected condition on the server. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchTrips: {
        parameters: {
            query: {
                /** @description The starting stop name (Source) */
                from: string;
                /** @description The destination stop name */
                to: string;
                /** @description Travel date in YYYY-MM-DD format */
                date: string;
                /** @description Filter by specific bus type */
                bus_type?: "AC" | "Non-AC" | "Sleeper" | "Semi-Sleeper" | "AC Sleeper" | "Non-AC Seater" | "Volvo Multi-Axle" | "AC Seater";
                /** @description Filter for buses departing after this time (HH:MM:SS) */
                departure_time?: string;
                /** @description Filter by specific boarding point name */
                boarding_point?: string;
                /** @description Filter by specific dropping point name */
                dropping_point?: string;
                /** @description Page number for pagination */
                page?: number;
                /** @description Number of results per page */
                limit?: number;
                /**
                 * @description Sort criteria in format `field:order`. Can separate multiple with commas.
                 *     Allowed fields: price, rating, departure_time, duration.
                 *     Allowed orders: asc, desc.
                 */
                sort?: string;
                /** @description Field to sort the results by */
                sort_by?: "price" | "rating" | "departure_time";
                /** @description Order of sorting */
                sort_order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        meta?: {
                            total?: number;
                            page?: number;
                            limit?: number;
                            totalPages?: number;
                        };
                        data?: components["schemas"]["BusSearchResult"][];
                    };
                };
            };
            400: components["responses"]["BadRequestError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getBookingsInfo: {
        parameters: {
            query: {
                /** @description The ID of the operator requesting the manifest. */
                operator_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful manifest response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description List of buses found for the operator. */
                        bus?: components["schemas"]["OperatorBusManifest"][];
                    };
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
